[ACS-8635] ADW: View button not working on create process
Alfresco/alfresco-ng2-components pull request #10121
Opened 2024-08-23 08:34 UTC by dominikiwanekhyland

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://hyland.atlassian.net/browse/ACS-8648

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-08-26 09:58 UTC, swapnil-verma-gl approved these changes

2024-08-26 17:04 UTC, DenysVuika requested changes

2024-08-26 17:04 UTC, DenysVuika commented on lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
> +        if (this.isTemporaryFile(file) || file.sourceId) {
please provide unit tests

2024-08-27 11:12 UTC, g-jaskowski approved these changes

2024-08-29 15:07 UTC, DenysVuika approved these changes

2024-08-29 15:07 UTC, merged