AAE-25888 Offset SearchTextInput expansion based on search icon width
Alfresco/alfresco-ng2-components pull request #10213
Opened 2024-09-13 14:57 UTC by wojd0

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://hyland.atlassian.net/browse/AAE-25888

Expandable search text input offset by approximate not full value to compensate for the search icon's width.

**What is the new behaviour?**

Expandable search text input offset by 100% minus actual search icon width.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-09-16 07:47 UTC, wojd0 commented on lib/core/src/lib/search-text/search-text-input.component.ts
> +        return this.expandable ? '48px' : '0px';
it's the combined padding and width coming from angular material's `.mat-mdc-form-field-icon-suffix` class
![Screenshot 2024-09-16 at 09 46 16](https://github.com/user-attachments/assets/493d9894-7244-4b24-8687-178bd3834c46)

2024-09-16 10:28 UTC, VitoAlbano requested changes

2024-09-16 10:28 UTC, VitoAlbano commented on lib/core/src/lib/search-text/search-text-input.component.ts
> +        return this.expandable ? '48px' : '0px';
Wouldn't this mean that, if something changes in the styles we will have a problem here? isn't there a more flexible approach to this issue?

2024-09-17 05:51 UTC, wojd0 commented on lib/core/src/lib/search-text/search-text-input.component.scss
> +
this approach should be more customization-friendly? WDYT?

2024-09-17 07:14 UTC, wojd0 commented on lib/core/src/lib/search-text/search-text-input.component.scss
> +
this approach using a separate class for the inactive search button state should be more customization-friendly

2024-09-19 14:34 UTC, VitoAlbano approved these changes

2024-09-19 15:31 UTC, merged