AAE-10529 Find a better way to fix clipped icons
Alfresco/alfresco-ng2-components pull request #10366
Opened 2024-11-04 12:40 UTC by fkindgen

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [x] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://hyland.atlassian.net/browse/AAE-10529
A temporary fix was applied to avoid clipping icons.

**What is the new behaviour?**
https://hyland.atlassian.net/browse/AAE-10529

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Relates to https://github.com/Alfresco/hxp-frontend-apps/pull/9745

2024-11-04 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=10366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=10366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ng2-components?pullRequest=10366) it.</sub>

2024-11-11 10:12 UTC, eromano approved these changes
@DenysVuika @MichalKinas can you help on review here?

2024-11-11 14:03 UTC, DenysVuika approved these changes

2024-11-12 08:26 UTC, MichalKinas requested changes
Looks like this is breaking change in ACA, sorry for late review yesterday there was a public holiday in Poland
<img width="615" alt="Zrzut ekranu 2024-11-12 o 09 25 37" src="https://github.com/user-attachments/assets/9ffde11e-8f08-43d3-994c-ca28b1959253">

2024-11-13 11:08 UTC, fkindgen commented
@MichalKinas Fixed the breaking change, please re-review.

2024-11-21 13:06 UTC, merged