Post release version bump
Alfresco/alfresco-ng2-components pull request #10417
Opened 2024-11-20 17:24 UTC by swapnil-verma-gl

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-11-20 17:29 UTC, MichalKinas requested changes

2024-11-20 17:29 UTC, MichalKinas commented on package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on package.json
> +  "version": "7.0.0-alpha.7-0",
This should point to next version

2024-11-20 17:29 UTC, MichalKinas commented on lib/testing/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/process-services/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/process-services-cloud/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/js-api/package.json
> +  "version": "8.0.0-alpha.7-0",
```suggestion
  "version": "8.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/insights/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/extensions/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/eslint-angular/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/core/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/content-services/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/cli/package.json
> +  "version": "7.0.0-alpha.7-0",
```suggestion
  "version": "7.0.0-alpha.7",
```

2024-11-20 17:29 UTC, MichalKinas commented on lib/cli/package.json
>    "author": "Hyland Software, Inc. and its affiliates",
In the same file js-api version should be updated to `"@alfresco/js-api": ">=8.0.0-alpha.7-0",`

2024-11-20 17:29 UTC, MichalKinas commented on lib/content-services/package.json
> +  "version": "7.0.0-alpha.7-0",
In the same file update the js-api and adf dependencies version to `8.0.0-alpha.7-0` and `7.0.0-alpha.7-0`

2024-11-20 17:29 UTC, MichalKinas commented on lib/content-services/package.json
> +  "version": "7.0.0-alpha.7-0",
Same for dependencies in other package.json files

2024-11-21 07:06 UTC, MichalKinas approved these changes

2024-11-21 10:42 UTC, MichalKinas approved these changes

2024-11-21 10:43 UTC, swapnil-verma-gl commented on lib/cli/package.json
> +    "@alfresco/js-api": ">=8.0.0-alpha.6-0",
This is ADF post release bump. The release has already happened

2024-11-21 10:56 UTC, MichalKinas commented on lib/cli/package.json
> +    "@alfresco/js-api": ">=8.0.0-alpha.6-0",
Yeah so it should use `>=8.0.0-alpha.7-0` now

2024-11-21 10:58 UTC, swapnil-verma-gl commented on lib/cli/package.json
> +    "@alfresco/js-api": ">=8.0.0-alpha.6-0",
I originally used that version only, but was getting failure in GHA. installDeps job on cli project was getting failed. See [here](https://github.com/Alfresco/alfresco-ng2-components/actions/runs/11948718606/job/33312909867#step:4:108)

2024-11-21 11:00 UTC, MichalKinas commented on lib/cli/package.json
> +    "@alfresco/js-api": ">=8.0.0-alpha.6-0",
Okay so let's leave it as is then

2024-11-21 11:00 UTC, merged