[ADF-994] Integrate SFS enhancements for Pagination component
Alfresco/alfresco-ng2-components pull request #2119
Opened 2017-07-24 13:46 UTC by chris-equis

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [x] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
`adf-pagination` no longer refers to the old `alfresco-pagination`

2017-07-24 14:03 UTC, DenysVuika requested changes

2017-07-24 14:03 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.html
> +    <span>{{ 'APP.PAGINATION.SHOW_RANGE' | translate: { range: range.join('-'), total: totalItems } }}</span>
Translation keys should be present in the `src/i18n/en.json` and probably needs "CORE" namespace for that as that file is currently empty.

2017-07-24 15:14 UTC, DenysVuika requested changes

2017-07-24 15:14 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-core/src/components/pagination/pagination.md
> +    (onPaginationEvent)="doSomething($event)"
I think those events are not implemented or replaced by the 'change' event.

2017-07-24 17:18 UTC, DenysVuika requested changes
-

2017-07-24 17:18 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.ts
> +    pageSizes: number[] = [ 25, 50, 100 ];
Needs to be "supportedPageSizes " to provide backwards compatibility.

2017-07-24 17:18 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.ts
> +    change: EventEmitter<PaginationQueryParams> = new EventEmitter<PaginationQueryParams>();
Needs the following events emitted to provide backwards compatibility
```ts
@Output()
changePageSize: EventEmitter<Pagination> = new EventEmitter<Pagination>();

@Output()
nextPage: EventEmitter<Pagination> = new EventEmitter<Pagination>();

@Output()
prevPage: EventEmitter<Pagination> = new EventEmitter<Pagination>();
```

2017-07-24 17:18 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-datatable/src/components/pagination/pagination.component.ts
> +    selector: 'alfresco-pagination',
Move both selectors to the core/pagination component and remove this implementation once backwards compatibility features are introduced.

2017-07-24 17:18 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
> +<alfresco-pagination *ngIf="isPaginationEnabled()"
Use adf-pagination here once the old one is deprecated

2017-07-24 17:18 UTC, DenisVuyka commented on ng2-components/ng2-alfresco-search/src/components/search.component.html
> +        <alfresco-pagination
Use adf-pagination here once the old one is deprecated

2017-07-25 14:27 UTC, chris-equis commented on ng2-components/ng2-alfresco-core/src/components/pagination/pagination.md
> +    (onPaginationEvent)="doSomething($event)"
Will update documentation soon

2017-08-02 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=2119) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=2119) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: chris-equis<br/>:x: Cristi Socea<br/><hr/>**Cristi Socea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ng2-components?pullRequest=2119) it.</sub>

2017-08-02 14:12 UTC, eromano commented
I think is missing a link to the pagination.md in the main Readme of the document. If we don't add it will be difficult for people find it

2017-08-04 12:25 UTC, eromano commented
there are ✖ 13 tests failed need to be fixed before to merge this story

2017-08-08 15:27 UTC, chris-equis commented
@eromano Travis passes, is there anything else for this PR? Thanks!

2017-08-08 15:37 UTC, merged