[ACA-3706] implement startedBy process filter property
Alfresco/alfresco-ng2-components pull request #6077
Opened 2020-08-26 13:52 UTC by SilviuCPopa

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://issues.alfresco.com/jira/browse/ACA-3706

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-08-26 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=6077) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=6077) before we can accept your contribution.<br/><hr/>**Silviu Popa** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ng2-components?pullRequest=6077) it.</sub>

2020-08-26 15:13 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> +                label: 'StartedBy',
should this be translated?

2020-08-26 15:15 UTC, DenysVuika requested changes

2020-08-26 15:15 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/process/process-filters/process-filters-cloud.module.ts
> +import { PeopleCloudModule } from '../../people/public-api';
should be imported directly from the module file, not public-api barrel, otherwise prod mode may have issues

2020-09-16 09:18 UTC, popovicsandras requested changes
Please see Denys' requests

2020-09-27 09:30 UTC, eromano commented
@SilviuCPopa is this PR still needed? if so can you bring it back in a mergeable state? thanks

2020-09-30 12:28 UTC, popovicsandras commented
Depends on the completedBy PR, as soon as that one is merged, we can rebase this. Anyway, this was moved to next version given its low priority.

2020-10-23 09:26 UTC, popovicsandras approved these changes

2020-10-23 09:33 UTC, merged