[ACA-3692] - Add completed date filter
Alfresco/alfresco-ng2-components pull request #6145
Opened 2020-09-21 15:37 UTC by SilviuCPopa

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://issues.alfresco.com/jira/browse/ACA-3692

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-09-21 15:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=6145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=6145) before we can accept your contribution.<br/><hr/>**Silviu Popa** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ng2-components?pullRequest=6145) it.</sub>

2020-09-22 08:55 UTC, VitoAlbano commented
Please fix the unit tests

2020-09-23 12:26 UTC, popovicsandras requested changes

2020-09-23 12:26 UTC, popovicsandras commented on lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> +            if (!property.rangeKeys) {
After the changes what we discussed, do we still need this dirty change? :P

2020-09-23 12:26 UTC, popovicsandras commented on lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
> +            this.completedFrom = obj.completedFrom || null;
Is it the last version, what we discussed? 🤔

2020-09-23 16:50 UTC, popovicsandras approved these changes
Given the close deadline, I approve it, but please for the marked duplication types create a separate Jira ticket in the next Technical Debt/Maintenance epic and assign to yourself and put into the sprint. (I think it is quite clear what I mean by the marked duplications, otherwise, let's discuss)

2020-09-23 16:50 UTC, popovicsandras commented on lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
> +    set completedFrom(completedFrom: string) {
Duplication type #1

2020-09-23 16:50 UTC, popovicsandras commented on lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> +            if (!!property.attributes) {
Duplication type #2

2020-09-24 09:07 UTC, merged