[AAE-3493] Update the documentation to provide the proper guidance on custom forms widgets for APA and APS developers
Alfresco/alfresco-ng2-components pull request #6158
Opened 2020-09-24 08:01 UTC by dhrn

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-09-24 17:11 UTC, m-hulbert requested changes
Let me know if I've understood the functionality correctly and this still makes sense and I can take a look at the APS stencil section too.

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +This is a short walkthrough on rendering custom AAE form widgets by means of custom Angular components.
```suggestion
This is an example of rendering custom form widgets using custom Angular components.
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +First let's create a basic form widget and call it `Custom Editor`:
```suggestion
To begin,  create a basic form widget and call it `Custom Editor`:
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +_Note the `type` value as it will become a `field type` value when corresponding form is rendered._
```suggestion
**Note**: The `type` is important as it will become the `field type` when the form is rendered.
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +Next put some simple html layout for [`Form`](../../lib/process-services/src/lib/task-list/models/form.model.ts)`runtime template` and [`Form`](../../lib/process-services/src/lib/task-list/models/for
```suggestion
Input some simple html for the [`Form`](../../lib/process-services/src/lib/task-list/models/form.model.ts)`runtime template` and the [`Form`](../../lib/process-services/src/lib/task-list/models/form.model.ts)`editor template` fields:
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +Now you are ready to design a test form based on your custom form widget:
```suggestion
You can now design a form that uses your custom form widget:
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +### Creating custom form widget
```suggestion
### Create a custom form widget
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +### Creating custom widget
```suggestion
### Create a custom widget
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +Once wired with a new task it should look like the following within AAE Process Experience:
```suggestion
When displayed in a task, the field will look similar to the following:
```

2020-09-24 17:11 UTC, m-hulbert commented on docs/user-guide/aae-extensions.md
> +![adf form widget runtime](../docassets/images/aae-resolved-widget.png)
```suggestion
To render the missing content:

1. Create an Angular component:

    ```ts
    import { Component } from '@angular/core';
    import { WidgetComponent } from '@alfresco/adf-core';
    @Component({
        selector: 'app-demo-widget',
        template: `<div style="color: green">ADF version of custom form widget</div>`
    })
    export class DemoWidgetComponent extends WidgetComponent {}
    ```

2. Place it inside the custom module:

    ```ts
    import { NgModule } from '@angular/core';
    import { DemoWidgetComponent } from './demo-widget.component';
    @NgModule({
        declarations: [ DemoWidgetComponent ],
        exports: [ DemoWidgetComponent ]
    })
    export class CustomWidgetsModule {}
    ```

3. Import it into your Application Module:

    ```ts
    @NgModule({
        imports: [
            // ...
            CustomWidgetsModule
            // ...
        ],
        providers: [],
        bootstrap: [ AppComponent ]
    })
    export class AppModule {}
    ```

4. Import the [`FormRenderingService`](../core/services/form-rendering.service.md) in any of your Views and provide the new mapping:

    ```ts
    import { Component } from '@angular/core';
    import { DemoWidgetComponent } from './demo-widget.component';
    @Component({...})
    export class MyView {
        constructor(formRenderingService: FormRenderingService) {
            this.formRenderingService.register({
                'custom-editor': () => DemoWidgetComponent
            });
        }
    }
    ```

At runtime you should now see your custom Angular component rendered in place of the original form widgets:

![adf form widget runtime](../docassets/images/aae-resolved-widget.png)
```

2020-09-25 10:53 UTC, m-hulbert approved these changes
LGTM 👍

2020-09-25 11:41 UTC, eromano approved these changes

2020-09-25 11:42 UTC, merged