[ACA-3010] - Process/Task Cloud fix wrong date range
Alfresco/alfresco-ng2-components pull request #6192
Opened 2020-09-30 10:52 UTC by SilviuCPopa

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://issues.alfresco.com/jira/browse/ACA-4010

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-09-30 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=6192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=6192) before we can accept your contribution.<br/><hr/>**Silviu Popa** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ng2-components?pullRequest=6192) it.</sub>

2020-09-30 12:24 UTC, popovicsandras approved these changes

2020-09-30 13:13 UTC, eromano approved these changes

2020-09-30 13:15 UTC, eromano requested changes
@SilviuCPopa an E2E related to this area is failing please give it a look it could highlight an issue

2020-09-30 13:29 UTC, SilviuCPopa commented
> @SilviuCPopa an E2E related to this area is failing please give it a look it could highlight an issue
The same failing e2e were failing in this PR https://github.com/Alfresco/alfresco-ng2-components/pull/6186
I excluded them and raised an issue (https://issues.alfresco.com/jira/browse/ADF-5261)  to be investigated.

2020-10-01 10:07 UTC, popovicsandras approved these changes

2020-10-01 10:10 UTC, merged