[AAE-3967] Add datetime-range search filter component
Alfresco/alfresco-ng2-components pull request #6297
Opened 2020-10-30 13:01 UTC by arditdomi

**Please check if the PR fulfills these requirements**

> - [X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [X] Tests for the changes have been added (for bug fixes / features)
> - [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [X] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://issues.alfresco.com/jira/browse/AAE-3967

**What is the new behaviour?**
- New datetime range component has been added
- The datetime searchable content model properties in attach file widget make use of it and display a datetime-picker range to be selected

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-11-02 18:05 UTC, eromano requested changes

2020-11-02 18:05 UTC, eromano commented on lib/content-services/src/lib/search/components/search-datetime-range/search-datetime-range.component.ts
> +            this.datetimePickerDateFormat = this.settings.datetimeFormat || DATE_TIME_FORMAT;
you can probably simplify here

2020-11-02 18:05 UTC, eromano commented on lib/content-services/src/lib/search/components/search-datetime-range/search-datetime-range.component.ts
> +    datetimePickerDateFormat = DATE_TIME_FORMAT;
do you assign it also down in the init?

2020-11-02 18:05 UTC, eromano commented on lib/content-services/src/lib/search/components/search-datetime-range/search-datetime-range.component.spec.ts
> +        expect(inputs[0]).toBeDefined();
is toBeTruthy enough?

2020-11-02 18:05 UTC, eromano commented on lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
> +        expect(component.getFromValidationMessage()).toBeFalsy();
falsy or empty message?

2020-11-02 18:05 UTC, eromano commented on lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
> +        expect(component.from).toBeDefined();
is defined in general or should it have a certain value?

2020-11-03 06:34 UTC, cristinaj commented on docs/content-services/components/search-datetime-range.component.md
> +
shouldn't be search-datetime-range.component.ts instead of search-date-range.component.ts?

2020-11-04 11:15 UTC, cristinaj approved these changes

2020-11-04 11:22 UTC, merged