[ACA-4053] Add appVersion multi-select dropdown in edit cloud process filter
Alfresco/alfresco-ng2-components pull request #6321
Opened 2020-11-05 15:10 UTC by arditdomi

**Please check if the PR fulfills these requirements**

> - [X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [X] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://alfresco.atlassian.net/browse/ACA-4053

**What is the new behaviour?**
The appVersion is now a dropdown which allows multi-selection
<img width="1464" alt="Screenshot 2020-11-05 at 3 09 36 pm" src="https://user-images.githubusercontent.com/32884230/98258582-f1e84600-1f78-11eb-9b87-1eec0148c33f.png">

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-11-05 15:17 UTC, arditdomi commented
blocked by https://alfresco.atlassian.net/browse/ACA-3713

2020-11-23 12:05 UTC, eromano requested changes

2020-11-23 12:05 UTC, eromano commented on demo-shell/src/app/components/cloud/processes-cloud-demo.component.html
> +            [appVersion]="editedFilter.appVersion"
can you just modify appVersion  to have string || string []

2020-11-23 13:42 UTC, mauriziovitale approved these changes

2020-11-23 13:56 UTC, eromano approved these changes

2020-11-24 03:15 UTC, merged