[AAE-3638] - implement priority drodpown widget
Alfresco/alfresco-ng2-components pull request #6351
Opened 2020-11-16 09:28 UTC by SilviuCPopa

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://alfresco.atlassian.net/browse/AAE-3638

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [x] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-11-16 09:41 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
>          service = new TaskCloudService(alfrescoApiMock,
can you inject this service via TestBed intead of calling ctor manually?

2020-11-17 10:07 UTC, DenysVuika requested changes

2020-11-17 10:07 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
>      get priorities(): any[] {
Please introduce an interface and provide proper typing in the return value

2020-11-17 11:06 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
> +        // alfrescoApiMock = new AlfrescoApiServiceMock(new AppConfigService(null), new StorageService());
commented code, not needed probably

2020-11-17 11:09 UTC, DenysVuika requested changes

2020-11-17 11:09 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
> +    priorities: any;
missing type

2020-11-17 11:09 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> +        this.taskListCloudService.getTaskByRequest(<TaskQueryCloudRequestModel> requestNode).pipe(
you don't need casting if `getTaskByRequest` returns correct result, or fix the `getTaskByRequest` to return it

2020-11-17 11:09 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> +    private replacePriorityValues(tasks: any) {
missing type

2020-11-17 11:09 UTC, DenysVuika commented on lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> +        const entries = tasks.list.entries.map((item: any) => {
missing type

2020-11-17 15:46 UTC, DenysVuika commented on lib/testing/src/lib/core/pages/card-view/card-view-select-item.page.ts
> +    async getReadonlyValue() {
missing return type

2020-11-17 15:48 UTC, DenysVuika approved these changes

2020-11-18 11:24 UTC, eromano approved these changes

2020-11-18 11:25 UTC, merged