[AAE-4127] [process-services] [APS1] Return Create Filters API response instead of the default payload
Alfresco/alfresco-ng2-components pull request #6370
Opened 2020-11-20 08:14 UTC by sivakumar414ram

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [x] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/AAE-4127

**What is the new behaviour?**

Returns API response instead of the payload used for creation

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-11-20 08:28 UTC, DenysVuika approved these changes

2020-11-20 09:20 UTC, eromano requested changes
unit test are missing

2020-11-20 14:59 UTC, sivakumar414ram commented
> unit test are missing

Added unit tests

2020-11-23 09:26 UTC, arditdomi approved these changes

2020-11-23 11:28 UTC, merged