[AAE-4569] Added readOnly property to breadcrumb components
Alfresco/alfresco-ng2-components pull request #6636
Opened 2021-02-05 11:32 UTC by TomikaArome

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-02-05 11:45 UTC, mauriziovitale commented on lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
> +        [ngSwitch]="last || readOnly"
can we create a method?

2021-02-05 12:18 UTC, arditdomi requested changes

2021-02-05 12:18 UTC, arditdomi commented on lib/content-services/src/lib/breadcrumb/breadcrumb.component.ts
> +    breadcrumbItemIsAnchor(lastItem) {
missing return type

2021-02-09 11:57 UTC, eromano approved these changes

2021-02-09 11:57 UTC, merged