[ACA-3881] Move the node to ps before loading
Alfresco/alfresco-ng2-components pull request #6700
Opened 2021-02-18 15:12 UTC by mauriziovitale

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-02-18 17:38 UTC, eromano requested changes
Missing description and unit test

2021-02-19 11:38 UTC, sivakumar414ram commented on lib/process-services/src/lib/process-list/components/start-process.component.ts
> +    movedNodeToPS;
Can we add type here
```suggestion
    movedNodeToPS: FormValues;
```

2021-02-19 11:45 UTC, sivakumar414ram reviewed
Please check the comments

2021-02-19 12:10 UTC, eromano approved these changes

2021-02-19 12:26 UTC, sivakumar414ram approved these changes

2021-02-19 13:25 UTC, merged