[ACA-4361] permission layout modified
Alfresco/alfresco-ng2-components pull request #6937
Opened 2021-04-19 05:34 UTC by dhrn

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/ACA-4361

**What is the new behaviour?**

fixed

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-04-19 14:40 UTC, eromano approved these changes

2021-04-20 10:32 UTC, davidcanonieto requested changes

2021-04-20 10:32 UTC, davidcanonieto commented on lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
> +    protected updateValue(person: Person, group: Group) {
could we simplify this logic, after all it's one or the other, always one of them is going to be null.

2021-04-20 10:32 UTC, davidcanonieto commented on lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
> +        const person = this.nodePermissionService.transformNodeToPerson(entry);
And same here, could we have a smart method that returns the corresponding Person/Group based on the node passed?

2021-04-20 10:39 UTC, dhrn commented on lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
> +        <mat-selection-list class="adf-permission-result-list-elements" (keydown.control.a)="selectAll( data?.list?.entries)">
yes it add all the result to selected list. it is not paginated (array of node entries from search result ).

2021-04-20 10:41 UTC, dhrn commented on lib/content-services/src/lib/permission-manager/components/add-permission/add-permission.component.ts
> +    private transformNodeToPermissionElement(nodes: NodeEntry[], nodeRole: any): PermissionElement[] {
it is string.. wrong type i will update it

2021-04-22 08:31 UTC, adinapitul commented on e2e/content-services/pages/permissions.page.ts
> +    emptyElement = new TestElement(this.rootElement.elementFinder.element(by.css('.adf-no-permission__template')));
this looks weird. Why is this element so complicated?

is something like this not working?
```
emptyElement = TestElement.byCss('.adf-no-permission__template');
```
or
```
rootSelector = 'adf-permission-manager-card';
emptyElement = TestElement.byCss(`${this.rootSelector} .adf-no-permission__template'`);
```

2021-04-22 08:31 UTC, adinapitul commented on e2e/content-services/pages/permissions.page.ts
> +
remove empty line

2021-04-22 08:31 UTC, adinapitul commented on e2e/content-services/pages/permissions.page.ts
> +    async waitVisible(): Promise<void> {
"visible" and "present" are not the same. Method name is misleading:waitVisible, when in fact inside you're waiting for presence.

2021-04-22 08:31 UTC, adinapitul commented on e2e/content-services/pages/permissions.page.ts
> +    async isErrored(): Promise<boolean> {
looking at the element name and selector, "emptyElement", ".adf-no-permission__template", I don't understand the name of this method "isErrored", or the name of the following method: "waitForError"
please find better / more relevant naming.
If ".adf-no-permission__template" really is an error, then the element should not be called "emptyElement"

2021-04-22 08:31 UTC, adinapitul commented on e2e/content-services/pages/permissions.page.ts
> +        const loader = new TestElement(this.rootElement.elementFinder.element(by.css('adf-permission-loader')));
please simplify the loader element definition. I'm sure there's a way without all this rootElement.elementFinder.element by.css .....

2021-04-22 11:23 UTC, adinapitul commented on e2e/content-services/pages/permissions.page.ts
> +    async waitTillContentLoads(): Promise<void> {
what's the purpose of isNotDisplayed? you're only using it for the log message? 
on the catch block, if isNotDisplayed is false, does this mean **IT IS** displayed? (I don't know who's "it" in this :) )

can you please explain what this method does?

2021-04-22 11:27 UTC, adinapitul commented on e2e/content-services/components/permissions-component.e2e.ts
> +            await browser.sleep(500);
sleep is still here. Why is it needed? Can you instead wait for something specific? for an element to be visible or not.... or something...

2021-04-23 07:50 UTC, merged