[AAE-5021] Add listPeople method to PeopleContentService
Alfresco/alfresco-ng2-components pull request #6947
Opened 2021-04-23 10:59 UTC by TomikaArome

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-04-23 11:07 UTC, DenysVuika requested changes

2021-04-23 11:07 UTC, DenysVuika commented on lib/core/mock/ecm-user.service.mock.ts
> +export let fakeEcmUser2 = {
use `const` over `let`
```suggestion
export const fakeEcmUser2 = {
```

2021-04-23 11:07 UTC, DenysVuika commented on lib/core/mock/ecm-user.service.mock.ts
>  export let fakeEcmUserNoImage = {
```suggestion
export const fakeEcmUserNoImage = {
```

2021-04-23 11:07 UTC, DenysVuika commented on lib/core/mock/ecm-user.service.mock.ts
> +export let fakeEcmUserList = {
```suggestion
export const fakeEcmUserList = {
```

2021-04-23 14:04 UTC, arditdomi requested changes

2021-04-23 14:04 UTC, arditdomi commented on lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
> +import { EcmUserModel } from '../../../../../../core/models/ecm-user.model';
Should be @alfresco/adf-core

2021-04-23 14:04 UTC, arditdomi commented on lib/content-services/src/lib/permission-manager/models/member.model.ts
> +import { EcmUserModel } from '../../../../../core/models/ecm-user.model';
Same

2021-04-23 14:04 UTC, arditdomi commented on lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
> +import { EcmUserModel } from '../../../../../core/models/ecm-user.model';
Same

2021-04-23 14:04 UTC, arditdomi commented on lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.spec.ts
> +import { EcmUserModel } from '../../../../../../core/models/ecm-user.model';
Same

2021-04-23 14:04 UTC, arditdomi commented on lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
> +import { EcmUserModel } from '../../../../../../core/models/ecm-user.model';
Same

2021-04-28 10:02 UTC, arditdomi approved these changes

2021-04-28 10:03 UTC, sivakumar414ram approved these changes

2021-04-28 15:50 UTC, merged