[AAE-5027] - Fix preselection for pagination - skipped selection/pres…
Alfresco/alfresco-ng2-components pull request #6976
Opened 2021-05-05 16:45 UTC by arditdomi

…election

**Please check if the PR fulfills these requirements**

> - [X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [X] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [X] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://alfresco.atlassian.net/browse/AAE-5027

**What is the new behaviour?**
In some cases not all the preselected nodes can be selected, for example: when the pagination does not allow a file to be shown and the node that we want to preselect is not part of the current rows. Once the pagination gets updated, (for example maxItems from 10 to 20), the preselected nodes that couldn't be selected in the first place should get selected now that they are visible in the document list. 

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-06 09:23 UTC, mauriziovitale approved these changes

2021-05-06 09:56 UTC, eromano reviewed
Do we still remove the selection when the user change page?

2021-05-06 10:06 UTC, arditdomi commented
> Do we still remove the selection when the user change page?

Yes we do

2021-05-06 14:30 UTC, eromano requested changes
Nope , the document list has to be agnostic of what kind of pagination is used

2021-05-06 16:41 UTC, mauriziovitale approved these changes

2021-07-08 12:52 UTC, eromano requested changes

2021-07-08 12:52 UTC, eromano commented on lib/content-services/src/lib/document-list/components/document-list.component.ts
> +        this._pagination.merge ? this.reloadWithoutResettingSelection() : this.reload();
reload() {
        this.ngZone.run(() => {
            this.resetSelection();
              if(this._pagination.merge){
                          this.reloadWithoutResettingSelection();
              }
        });
    }

2021-07-08 12:52 UTC, eromano commented on lib/content-services/src/lib/document-list/components/document-list.component.ts
> +        this._pagination.merge ? this.reloadWithoutResettingSelection() : this.reload();
to me looks better leave all thsi responsibility in the reload method

2021-07-08 12:52 UTC, eromano commented on lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
> -            const listPrunedDuplicate = shareDataRows.filter((elementToFilter: any) => {
why you want to remove this logic?

2021-09-06 14:25 UTC, arditdomi commented
Closing it for now. It is very hard to implement a fix and it impacts a lot of areas.

2021-09-06 14:25 UTC, closed without merging