[AAE-5128] [APA] Drag and Drop template is broken on Upload from your device tab
Alfresco/alfresco-ng2-components pull request #6983
Opened 2021-05-07 12:09 UTC by sivakumar414ram

… 

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/AAE-5128

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-08 10:32 UTC, eromano approved these changes

2021-05-10 08:11 UTC, TomikaArome approved these changes

2021-05-10 10:11 UTC, mauriziovitale requested changes
Use a pipe pure

2021-05-11 12:57 UTC, sivakumar414ram commented
Fixed in this pr https://github.com/Alfresco/alfresco-ng2-components/pull/7013

2021-05-11 12:57 UTC, closed without merging