[ADF-5393] Move node update from ACA to viewer-core component
Alfresco/alfresco-ng2-components pull request #6984
Opened 2021-05-07 14:42 UTC by ursedaniel

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/ADF-5393

**What is the new behaviour?**

Move node update from ACA to viewer-core component

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-07 14:44 UTC, ursedaniel commented
discussed with @eromano to move the update login from outside viewer - inside the core component

2021-05-07 14:49 UTC, eromano approved these changes

2021-05-08 07:34 UTC, DenysVuika requested changes

2021-05-08 07:34 UTC, DenysVuika commented on demo-shell/src/app/components/app-layout/app-layout.component.scss
> +        z-index: 1100;
do we need this in the demo shell? does that mean every application needs to have this? if not, then let's have this as part of the uploading dialog styles

2021-05-08 07:34 UTC, DenysVuika commented on lib/core/viewer/components/viewer.component.ts
> +        const newImageFile: File = new File([newImageBlob], this?.nodeEntry?.entry?.name, { type: this?.nodeEntry?.entry?.content?.mimeType });
you can move this line inside the if-block as there's a chance it is not needed based on the condition below

2021-05-08 21:30 UTC, closed without merging