[ACA-4325] - disable upload button on upload new file version begin
Alfresco/alfresco-ng2-components pull request #7017
Opened 2021-05-11 15:25 UTC by SilviuCPopa

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://alfresco.atlassian.net/browse/ACA-4325

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-11 16:26 UTC, eromano approved these changes

2021-05-12 09:04 UTC, ursedaniel approved these changes

2021-05-12 10:32 UTC, eromano commented
@SilviuCPopa many e2e related to upload are failing can you check it?

2021-05-12 14:26 UTC, eromano requested changes

2021-05-12 14:26 UTC, eromano commented on lib/content-services/src/lib/version-manager/version-upload.component.ts
> +    uploadStarting = new EventEmitter<FileUploadEvent>();
started probably is better than starting?

2021-05-12 15:43 UTC, eromano approved these changes

2021-05-12 16:17 UTC, merged