[ACA-2864] Site Managers are not able to disable inherit permissions …
Alfresco/alfresco-ng2-components pull request #7021
Opened 2021-05-12 16:52 UTC by dhrn

…in DW/ACA

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://alfresco.atlassian.net/browse/ACA-2864

Sitemanger can't toggle Inherit permission

**What is the new behaviour?**

fix

What is the fix?
We should include the site_manger group to node before toggling the inherit permission

why are doing this hack?
As soon as we toggle the inherit permission user can't get the access to the node. so we should include to the locallyset before toggling the inherit permission.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-12 17:00 UTC, eromano requested changes

2021-05-12 17:00 UTC, eromano commented on lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.service.ts
> +    private hasLocalPermission(node: Node) {
missing return types

2021-05-12 17:11 UTC, adinapitul requested changes
I want to review this approach cause it sounds a bit dangerous. Please allow me time till tomorrow morning.

@dhrn , why do you say this "As soon as we toggle the inherit permission user can't get the access to the node." ?

2021-05-12 17:13 UTC, dhrn commented
@adinapitul this is how share  is doing.

2021-05-12 17:16 UTC, dhrn commented
> I want to review this approach cause it sounds a bit dangerous. Please allow me time till tomorrow morning.
> 
> @dhrn , why do you say this "As soon as we toggle the inherit permission user can't get the access to the node." ?

@adinapitul backend is smart. it won't allow the user to make this possible. what i mean if we didn't include then togglerpermission api will be failed.

2021-05-13 09:38 UTC, adinapitul approved these changes
@dhrn , @eromano , I performed some checks and I think this is fine after all. 
My concern was mainly related to complex scenarios involving adding then removing user from the site, or adding then removing user from the system group.... 
But indeed, this is what share is doing also. 

We're fine. Thank you!

2021-05-13 09:42 UTC, eromano approved these changes

2021-05-14 13:12 UTC, merged