[AAE-5208] Add pagination info to listPeople function in PeopleContentService
Alfresco/alfresco-ng2-components pull request #7055
Opened 2021-05-24 13:42 UTC by TomikaArome

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/AAE-5208

**What is the new behaviour?**

listPeople function returns pagination info as well as entries.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-24 14:02 UTC, arditdomi requested changes
Can you please update the documentation with the new stuff?

2021-05-26 10:20 UTC, arditdomi approved these changes

2021-05-26 10:27 UTC, sivakumar414ram approved these changes

2021-05-26 11:16 UTC, mauriziovitale approved these changes

2021-06-02 10:49 UTC, merged