[AAE-6310] Fix for attaching files
Alfresco/alfresco-ng2-components pull request #7457
Opened 2022-01-19 11:47 UTC by BSekula

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://alfresco.atlassian.net/browse/AAE-6310

After navigate to process page with query params for process i.e. `process="my-proess-name"` form and attached files were not shown   

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-01-19 11:47 UTC, BSekula commented on lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
> +                            >
Indention only

2022-01-19 11:49 UTC, BSekula commented on lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
>                      }
Only added part here is:

```
const processDefinition = this.processDefinitionList.find(process => process.name === this.processDefinitionName);
  if (processDefinition) {
    this.filteredProcesses = this.getProcessDefinitionListByNameOrKey(processDefinition.name);
    this.setProcessDefinitionOnForm(processDefinition.name);
    this.processDefinitionSelectionChanged(processDefinition);
}
```
rest are indentations

2022-01-19 12:07 UTC, Qetikv approved these changes

2022-01-20 10:08 UTC, eromano commented
@BSekula can we avoid the indentation change? thanks

2022-01-20 10:12 UTC, eromano requested changes
commented added

2022-01-20 10:25 UTC, BSekula commented
reverted indentation changes

2022-01-20 14:17 UTC, eromano approved these changes

2022-01-24 11:36 UTC, merged