Fetch the userInfo once loggedIn and expose the capability of admin
Alfresco/alfresco-ng2-components pull request #7682
Opened 2022-06-21 16:25 UTC by mauriziovitale

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-06-22 10:48 UTC, arditdomi reviewed
You also need to update the docs about the services you changed

2022-06-22 10:48 UTC, arditdomi commented on lib/core/services/auth-guard-base.ts
> +        protected userService: PeopleContentService
Shall we name it peopleContentService instead of user service?

2022-06-22 10:48 UTC, arditdomi commented on lib/core/userinfo/components/user-info.component.ts
> +    constructor(private ecmUserService: PeopleContentService,
I suggest we name the service to match the service class name, in this case `peopleContentService`

2022-06-23 13:40 UTC, arditdomi commented on lib/core/services/people-content.service.ts
> +            this.resetLocalCurrentUser();
is there a unit test about this?

2022-06-23 13:42 UTC, arditdomi commented on lib/core/services/people-content.service.ts
> +            this.resetLocalCurrentUser();
oh yes it's covered, looks good

2022-06-23 13:42 UTC, arditdomi approved these changes
Good job 👏

2022-06-23 18:53 UTC, DenysVuika requested changes

2022-06-23 18:53 UTC, DenysVuika commented on lib/core/services/people-content.service.ts
>  export enum ContentGroups {
can you just move the enum to a separate file? this will allow not using the eslit-disable hack

2022-06-23 18:53 UTC, DenysVuika commented on lib/core/services/user-info-resolver.service.ts
> +    _route: ActivatedRouteSnapshot,
you can remove the parameters instead of prefixing them, the JS/TS allow that

2022-06-24 08:50 UTC, DenysVuika approved these changes

2022-06-27 10:15 UTC, mauriziovitale commented
@DenysVuika I only had to change the test because affected by the refactoring 
btw we should decide what a unit test of a service should test. 

In the above case, the error is making sure there is a catch and a throw and in my opinion, this should be checked because sometimes the developer forgets to add the catch. 
For the others the unit is mocking the js api an testing the result is correctly mapped (no entry is returned)

2022-06-27 11:02 UTC, merged