Fix: Button have descernible text, banner landmark, contentinfo landm…
Alfresco/alfresco-ng2-components pull request #7858
Opened 2022-09-23 13:31 UTC by rbahirsheth

…ark issue

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
issues in version dialog
1. descernible text
2. banner landmark
3. contentinfo landmark

**What is the new behaviour?**
Fix: Button have descernible text, banner landmark, contentinfo landmark issues

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-09-23 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=7858) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-ng2-components?pullRequest=7858) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-ng2-components?pullRequest=7858) it.</sub>

2022-09-23 13:41 UTC, DenysVuika requested changes

2022-09-23 13:42 UTC, DenysVuika commented
Please add the JIRA ticket name to the PR title so that it gets mapped with the JIRA

2022-09-27 08:13 UTC, rbahirsheth commented on lib/content-services/src/lib/version-manager/version-list.component.html
> +            <button mat-icon-button [matMenuTriggerFor]="versionMenu" [id]="'adf-version-list-action-menu-button-'+version.entry.id" title="Manage version options">
fixed title with | translate

2022-09-27 09:50 UTC, DenysVuika approved these changes

2022-10-04 11:47 UTC, nikita-web-ua approved these changes

2022-10-06 08:18 UTC, merged