[ACS-3551] a11y fix for search results view
Alfresco/alfresco-ng2-components pull request #7881
Opened 2022-10-06 07:47 UTC by arohilaGL

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [x] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

Accessibility issues on search results page

**What is the new behaviour?**

Accessibility issues on search results page fixed.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-10-18 12:30 UTC, MichalKinas requested changes

2022-10-18 13:20 UTC, TomikaArome approved these changes

2022-10-19 06:15 UTC, MichalKinas approved these changes

2022-10-19 06:21 UTC, arohilaGL commented on lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.html
> +role="listbox"
changed the indentation

2022-10-19 10:38 UTC, nikita-web-ua approved these changes

2022-10-21 09:34 UTC, merged