[ACS-4051] 880196 CSV issue addressed
Alfresco/alfresco-ng2-components pull request #8119
Opened 2023-01-10 13:27 UTC by jatin2008

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

There was no way to perform the function using only the keyboard on the same screen or on a qualifying conforming alternate version.

**What is the new behaviour?**

using the keyboard we can copy the link to clipboard that was earlier not able to perform.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-01-10 13:37 UTC, nikita-web-ua approved these changes

2023-01-10 14:22 UTC, DenysVuika requested changes

2023-01-10 14:22 UTC, DenysVuika commented on lib/core/src/lib/clipboard/clipboard.directive.ts
> +    handleKeyDown(event: KeyboardEvent){
missing unit test for the new code

2023-01-11 08:29 UTC, jatin2008 commented on lib/core/src/lib/clipboard/clipboard.directive.ts
> +    handleKeyDown(event: KeyboardEvent){
unit test cases added for directive.

2023-01-13 17:17 UTC, DenysVuika approved these changes

2023-01-13 17:18 UTC, merged