[AAE-12288] Enable Environment Id filtering support
Alfresco/alfresco-ng2-components pull request #8360
Opened 2023-03-13 12:54 UTC by DiogoABastos

…and service-tasks

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
Process instances, user tasks and service tasks ADF components did not support environment id filtering.

**What is the new behaviour?**
Process instances, user tasks and service tasks ADF components now support environment id filtering.

**Does this PR introduce a breaking change?** (check one with "x")

> - [x] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-03-13 13:20 UTC, alep85 requested changes

2023-03-13 13:20 UTC, alep85 commented on lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> +    environmentList: any[] = [];
we should avoid the use of `any` type if is possible

2023-03-13 13:20 UTC, alep85 commented on lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> +                        if (application.environmentId) {
unit tests are missing

2023-03-13 13:20 UTC, alep85 commented on lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
> +    environmentList: any[] = [];
same here about avoiding `any`

2023-03-21 13:13 UTC, alep85 commented on lib/process-services-cloud/src/lib/common/public-api.ts
> +export * from './mock/index';
I'm not sure we need to export the mock, we shouldn't add it to the final bundle
@eromano @popovicsandras what do you think?

2023-03-28 13:30 UTC, eromano requested changes
can you update also the documentation?

2023-04-03 14:20 UTC, andrea-ligios approved these changes

2023-04-03 14:22 UTC, eromano approved these changes

2023-04-04 15:12 UTC, merged