HXOR-99 [ci:force] commits on adf is not working properly
Alfresco/alfresco-ng2-components pull request #8427
Opened 2023-03-30 10:12 UTC by DawidJablon

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [X] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
There is a issue with ci:force

**What is the new behaviour?**
Corrected issue with ci:force like it works in alfresco apps. 

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-03-30 10:36 UTC, maurizio-cacace requested changes

2023-03-30 10:36 UTC, maurizio-cacace commented on .github/workflows/pull-request.yml
> +          elif [[ "$COMMIT_MESSAGE" == "[ci:force]" ]]; then
```suggestion
          elif [[ "$COMMIT_MESSAGE" == "*[ci:force]*" ]]; then
```

2023-03-30 12:44 UTC, maurizio-cacace requested changes

2023-03-30 12:44 UTC, maurizio-cacace commented on .github/workflows/pull-request.yml
> +        uses: alfresco-build-tools/.github/actions/get-commit-message/action.yml
you need to put the tag (in this case @v1.36.0 ) when you use an external action

2023-03-30 15:15 UTC, maurizio-cacace requested changes

2023-03-30 15:32 UTC, DawidJablon commented on .github/workflows/pull-request.yml
> +          elif [[ "$COMMIT_MESSAGE" == "*[ci:force]*" ]]; then
Corrected in new commit

2023-03-31 08:30 UTC, maurizio-cacace approved these changes

2023-03-31 09:27 UTC, merged