[ACS-5308] Highlight the selected filter in ADW
Alfresco/alfresco-ng2-components pull request #8649
Opened 2023-06-12 11:01 UTC by Yasa-Nataliya

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**
When I click on any menu item in files this adf-active class does not remove, so I have added an active class based on the route.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://alfresco.atlassian.net/browse/ACS-5306.
There is a dependency between this PR and this one: https://github.com/Alfresco/alfresco-applications/pull/241.

2023-06-12 11:41 UTC, DenysVuika commented on lib/process-services/src/lib/process-list/components/process-filters.component.ts
> +        return this.currentRoute.includes('process') && this.currentFilter === filter;
you can do this in the "subcribe" section on the init, and assign to the Boolean property, without calculating each time from the html template

2023-06-12 11:42 UTC, DenysVuika commented on lib/process-services/src/lib/process-list/components/process-filters.component.ts
> +        this.iconsMDL = new IconModel();this.router.events
missing new line

2023-06-12 11:42 UTC, DenysVuika commented on lib/process-services/src/lib/task-list/components/task-filters.component.ts
> +        return this.currentRoute.includes('task') && this.currentFilter === filter;
same as for the process filter, evaluate the flag inside `.subscribe((navigationStart: NavigationStart)`

2023-06-12 12:55 UTC, DenysVuika commented on lib/process-services/src/lib/process-list/components/process-filters.component.ts
> +            this.currentRoute = navigationStart.url;
you probably don't need this variable, as component is not using "currentRoute" other than on the next line

2023-06-12 12:56 UTC, DenysVuika commented on lib/process-services/src/lib/task-list/components/task-filters.component.ts
> +                this.currentRoute = navigationStart.url;
you can replace with local variable
```suggestion
                const currentRoute = navigationStart.url;
```

2023-06-12 12:57 UTC, DenysVuika requested changes

2023-06-12 12:57 UTC, DenysVuika commented on lib/process-services/src/lib/process-list/components/process-filters.component.ts
> +    currentRoute: string= '';
not used anywhere

2023-06-12 12:59 UTC, DenysVuika commented
@Yasa-Nataliya please add unit tests for the changed/added code

2023-06-13 12:32 UTC, Yasa-Nataliya commented on lib/process-services/src/lib/task-list/components/task-filters.component.ts
> +                this.currentRoute = navigationStart.url;
Replaced

2023-06-13 12:33 UTC, DenysVuika approved these changes

2023-06-13 12:34 UTC, Yasa-Nataliya commented on lib/process-services/src/lib/task-list/components/task-filters.component.ts
> +    currentRoute: string = '';
I have removed it

2023-06-13 17:19 UTC, DenysVuika commented
@Yasa-Nataliya I have fixed some code issues in your PR, but you need to address the failing e2e caused by this PR

2023-06-13 18:05 UTC, Yasa-Nataliya commented
> @Yasa-Nataliya I have fixed some code issues in your PR, but you need to address the failing e2e caused by this PR

Thanks @DenysVuika, I'll take a look and address the failing e2e test

2023-06-16 09:49 UTC, DenysVuika approved these changes

2023-06-16 09:50 UTC, merged