[ACA-4313] - Sort order doesn't work correctly
Alfresco/alfresco-ng2-components pull request #8892
Opened 2023-09-08 10:22 UTC by DominikIwanek

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
When changing sorting in files and opening and closing preview for a file, the sorting is not applied correctly.

**What is the new behaviour?**
Proper sorting is applied every time it is set.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-09-08 12:09 UTC, MichalKinas approved these changes

2023-09-08 14:40 UTC, eromano requested changes

2023-09-08 14:40 UTC, eromano commented on lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> +            return sorting &&
when condition becomes so long in orther to improve the redability would be better move them in a private method with a name that explain what we are checking

2023-09-12 09:10 UTC, DenysVuika approved these changes

2023-09-12 13:58 UTC, eromano approved these changes

2023-09-12 14:07 UTC, merged