[AAE-19372] fix assignee input not being clickable
Alfresco/alfresco-ng2-components pull request #9228
Opened 2024-01-11 15:56 UTC by wojd0

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/AAE-19372

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-01-11 17:19 UTC, VitoAlbano requested changes

2024-01-11 17:19 UTC, VitoAlbano commented on lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> +            console.log(this.properties);
console.log 🗡️

2024-01-12 09:41 UTC, VitoAlbano approved these changes

2024-01-12 09:42 UTC, eromano approved these changes

2024-01-12 13:27 UTC, merged