AAE-21392 Fix dropdown cloud widget style
Alfresco/alfresco-ng2-components pull request #9457
Opened 2024-03-22 12:30 UTC by DiogoABastos

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [x] Other... Please describe:
Style update

**What is the current behaviour?** (You can also link to an open issue here)
Dropdown cloud widget with broken styles after Angular 15 migration

**What is the new behaviour?**
Dropdown cloud widget has the correct styles applied

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-03-25 11:50 UTC, popovicsandras approved these changes

2024-03-25 11:57 UTC, VitoAlbano requested changes

2024-03-25 11:57 UTC, VitoAlbano commented on lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
> +            const placeholderElement = fixture.debugElement.query(By.css('.mat-mdc-select-placeholder'));
Please use the Harness and not target directly the material selector

2024-04-04 16:16 UTC, VitoAlbano commented
This branch needs to be rebased or recreated from the main NG15 branch

2024-04-10 14:00 UTC, closed without merging

2024-04-10 14:00 UTC, DiogoABastos commented
Branch was recreated due to massive rebase required