AAE-21393 Fix amount widget style
Alfresco/alfresco-ng2-components pull request #9570
Opened 2024-04-17 14:10 UTC by DiogoABastos

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [x] Other... Please describe:
Style fix

**What is the current behaviour?** (You can also link to an open issue here)
Amount widget with broken styles after Angular 15 migration

**What is the new behaviour?**
Amount widget has the correct styles applied

<img width="726" alt="Screenshot 2024-04-17 at 15 09 52" src="https://github.com/Alfresco/alfresco-ng2-components/assets/50139916/6a6d7d64-0f42-424a-bf6e-207a0eac65af">

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-04-17 14:16 UTC, VitoAlbano requested changes

2024-04-17 14:16 UTC, VitoAlbano commented on lib/core/src/lib/form/components/widgets/amount/amount.widget.html
> +                     <label class="adf-label" *ngIf="!field.leftLabels" [attr.for]="field.id">{{field.name | translate }}<span class="adf-asterisk" *ngIf="isRequired()">*</span></label>
can you double check on the Material spec if here we need label or mat-label?

2024-04-17 14:16 UTC, VitoAlbano commented on lib/core/src/lib/form/components/widgets/amount/amount.widget.html
> +                     <span matTextPrefix class="adf-amount-widget__prefix-spacing">{{ currency }} &nbsp;</span>
Can we still have the prefix before the input ? it might be confusing otherwise

2024-04-24 13:53 UTC, closed without merging

2024-04-24 13:53 UTC, DiogoABastos commented
Recreated